name: $(Build.BuildID)

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      
  - task: DotNetCoreCLI@2
    displayName: 'restore'
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      
  - task: DotNetCoreCLI@2
    displayName: 'build'
    inputs:
      command: 'build'
      
  - task: Docker@2
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    inputs:
      containerRegistry: 'official-docker-modmoto'
      repository: 'modmoto/it-works-on-my-machine-org'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildID),
        latest

  - task: CopyFiles@2
    displayName: publish docker-compose files
    inputs:
      contents: '**/*docker-compose.yml'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)