version: '3.9'
services:
  it-works-on-my-machine-org:
    image: modmoto/it-works-on-my-machine-org:${TAG}
    container_name: it-works-on-my-machine-org-${CONTAINER_SUFFIX}
    restart: unless-stopped
    expose:
      - 80
    environment:
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
  
  mongo-db:
    image: mongo
    container_name: mongo-db-it-works-on-my-machine-org-${CONTAINER_SUFFIX}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    command: --wiredTigerCacheSizeGB=1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${DB_SECRET}
    volumes:
      - mongo-db-fading-flame:/data/db
  
networks:
  default:
    external:
      name: caddy

volumes:
  mongo-db-fading-flame:
    name: mongo-db-it-works-on-my-machine-org-${CONTAINER_SUFFIX}