version: '3.9'
services:
  fading-flame:
    image: modmoto/it-works-on-my-machine-org:${TAG}
    container_name: it-works-on-my-machine-org-${CONTAINER_SUFFIX}
    restart: unless-stopped
    expose:
      - 80

networks:
  default:
    external:
      name: caddy